### PR TITLE
Fix issue #104 Jain slee build always inserts it's configuration in standalone.xml

### PR DESCRIPTION
**Pull request by duyanh030**
Please refer #104

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks @duyanh030 !  @SergeyLee can you please review ?

**Comment by SergeyLee** [comment]
Thanks @duyanh030 ! I will review it today.

**Comment by deruelle** [comment]
@SergeyLee was this reviewed ?

**Comment by satanatoly** [comment]
closing, fixed with https://github.com/RestComm/jain-slee/commit/99911ac837cffe4a0505965bb751bb60eb217d8f and https://github.com/RestComm/jain-slee/commit/4adc8ee45045e57c6795bd4d901f364273ee251f

**Pull request closed without merging**
