### PR TITLE
 Add env-entry in gui slee-management-console Sbb specific information panel

### PR DESCRIPTION
**Pull request by duyanh030**
fix for issue #97

### CODE REVIEW

**Comment by nhanth87** [comment]
Hi Duy Anh,
I didn't see any html/js code for https://github.com/RestComm/jain-slee/tree/master/tools/slee-management-console?

Br,
TN

**Comment by duyanh030** [comment]
Hi Nhan. 

Slee-management -console use google gwt web toolkit module.   With the small changes in UI,  HTML and js are generated automatically base on java code. So we don't need HTML/js modification. 

Regards
Anh Dao

**Comment by nhanth87** [comment]
nice to hear that 👍

**Comment by deruelle** [comment]
@duyanh030 can you sign the Contributor License Agreement at https://telestax.com/open-source/#Contribute so your contributions can be accepted ?

**Comment by deruelle** [comment]
Thanks @duyanh030 for signing the contributor license agreement. @SergeyLee can you please review ?

**Comment by deruelle** [comment]
@SergeyLee were you able to review this PR ?

**Pull request merged**
